id = "v"
name = "V (Vlang)"
description = "V language support."
version = "0.4.2"
schema_version = 1
authors = ["lv37 <132778382+lv37@users.noreply.github.com>"]
repository = "https://github.com/lv37/zed-v"

[grammars.v]
repository = "https://github.com/lv37/v-tree-sitter"
commit = "8a380d4e12220748cbc0106cafd958f32ec8ecfc"

[language_servers.v]
languages = ["V"]
name = "LanguageServer.v"
