id = "v"
name = "V (Vlang)"
description = "V language support."
version = "0.4.0"
schema_version = 1
authors = ["lv37 <132778382+lv37@users.noreply.github.com>"]
repository = "https://github.com/lv37/zed-v"

[grammars.v]
repository = "https://github.com/lv37/v-tree-sitter"
commit = "764882164bcc91414a7cf861bfe495847f6dff87"

[language_servers.v]
languages = ["V"]
name = "LanguageServer.v"
